# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa35bf95f2a2c09732b66ec2a887420ea5dcae930c0c9325b79e526f75a929db9d0cf494f3df0724961df835fd54d1bffb815d24a59b9faa1d535d3e525f5bb8

test:
  secret_key_base: 5553880a00241e4a7b0c405d9765b2b255d47e924198e8e79f2a05b9bba1e2796dd8e18988c86c7003339770c3c325f455c3a77a92639c361156f7e8f4ed4d3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
